### ISSUE TITLE
Feature 1 & 2: User can login + view their profile page with an overview of their Spotify account.

### ISSUE THREAD

**Issue by justintaeson** [justintaeson/spotif.i#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their profile page that shows an overview of their Spotify information.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-04-18 at 11 24 23 AM](https://user-images.githubusercontent.com/97268025/163856655-fee676cf-eb87-4206-916d-bc1475690d19.png)
![Screen Shot 2022-04-18 at 11 24 16 AM](https://user-images.githubusercontent.com/97268025/163856660-7c6033f3-f075-48cb-8720-082738972d4e.png)
![Screen Shot 2022-04-18 at 11 29 42 AM](https://user-images.githubusercontent.com/97268025/163856662-3b52f47a-f306-4b01-8741-12d62ed99439.png)
![Screen Shot 2022-04-18 at 11 29 23 AM](https://user-images.githubusercontent.com/97268025/163856663-4a4c12d5-7e20-426d-9509-aca3621db759.png)
![Screen Shot 2022-04-18 at 11 33 07 AM](https://user-images.githubusercontent.com/97268025/163856784-cdb45595-4a79-4eb1-9d5d-e3b86ac895cf.png)
![Screen Shot 2022-04-18 at 11 32 58 AM](https://user-images.githubusercontent.com/97268025/163856785-1df99021-d838-4a63-8871-d39aa4aacec9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to grab user's Spotify account information (profile photo, username, userId, email, followers, subscription status, and country.
- [x] Test with HTTPie to make sure the data is pulling.
- [x] Make sure tokens get refreshed when the current token expires.
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for the bottom nav bar.
- [x] Create a page component to render the profile page.
- [x] Create an app component to render the profile page React element.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
