### ISSUE TITLE
Feature 3: User can view their top tracks of all time.

### ISSUE THREAD

**Issue by justintaeson** [justintaeson/spotif.i#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their top tracks of all time.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to see their top tracks of all time since they've had their Spotify account.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-04-19 at 10 57 31 AM](https://user-images.githubusercontent.com/97268025/164066359-e420c7f4-935d-4261-bb2c-853facb53f1f.png)
![Screen Shot 2022-04-19 at 10 57 23 AM](https://user-images.githubusercontent.com/97268025/164066363-7d0ed732-cd5d-4124-87f1-dcfa6da015ad.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Test the top tracks data with HTTPie.
- [x] Create a route to handle GET requests from the client once the user has been authorized.
- [x] In the route, fetch the top tracks data from the Spotify API with the needed credentials.
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to render the data onto the page.
- [x] Update the state to pull data for the top tracks of all time.
- [x] Style the page to make sure the data looks presentable on the browser.
- [x] Make sure the page is rendered when the user clicks on the tracks icon.
- [x] Make sure the page is rendering every time the page refreshes.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
