### ISSUE TITLE
Feature 4: User can view their top artists of all time.

### ISSUE THREAD

**Issue by justintaeson** [justintaeson/spotif.i#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their top artists of all time.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can see their most listened to artists ever since they had a Spotify account.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="174" alt="Screen Shot 2022-04-22 at 11 03 38 AM" src="https://user-images.githubusercontent.com/97268025/164769913-98dafe93-7af5-4470-bf16-4901d392b377.png">
<img width="440" alt="Screen Shot 2022-04-22 at 11 03 26 AM" src="https://user-images.githubusercontent.com/97268025/164769919-28fc682f-1020-413d-a6e6-ee6d0b973be9.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Test the top artists data with HTTPie.
- [x] Create a route to handle GET requests from the client once the user has been authorized.
- [x] In the route, fetch the top artists data from the Spotify API with the needed credentials.
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to render the data onto the page.
- [x] Update the state to pull data for the top artists of all time.
- [x] Style the page to make sure the data looks presentable on the browser.
- [x] Make sure the page is rendered when the user clicks on the tracks icon.
- [x] Make sure the page is rendering every time the page refreshes.

### 🧑‍⚕️ Clean Up

- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
